<?php
declare(strict_types=1);

return [
    371 => ['abbreviation' => 'CAD', 'scale' => 1, 'name' => 'Канадский доллар'],
    394 => ['abbreviation' => 'KWD', 'scale' => 1, 'name' => 'Кувейтский динар'],
    421 => ['abbreviation' => 'SGD', 'scale' => 1, 'name' => 'Сингапурского доллара'],
    426 => ['abbreviation' => 'CHF', 'scale' => 1, 'name' => 'Швейцарский франк'],
    429 => ['abbreviation' => 'GBP', 'scale' => 1, 'name' => 'Фунта стерлингов'],
    431 => ['abbreviation' => 'USD', 'scale' => 1, 'name' => 'Доллар США'],
    440 => ['abbreviation' => 'AUD', 'scale' => 1, 'name' => 'Австралийский доллар'],
    441 => ['abbreviation' => 'BGN', 'scale' => 1, 'name' => 'Болгарский лев'],
    448 => ['abbreviation' => 'NZD', 'scale' => 1, 'name' => 'Новозеландский доллар'],
    449 => ['abbreviation' => 'UAH', 'scale' => 100, 'name' => 'Гривен'],
    450 => ['abbreviation' => 'DKK', 'scale' => 10, 'name' => 'Датских крон'],
    451 => ['abbreviation' => 'EUR', 'scale' => 1, 'name' => 'Евро'],
    452 => ['abbreviation' => 'PLN', 'scale' => 10, 'name' => 'Злотых'],
    453 => ['abbreviation' => 'ISK', 'scale' => 100, 'name' => 'Исландских крон'],
    454 => ['abbreviation' => 'MDL', 'scale' => 10, 'name' => 'Молдавских леев'],
    455 => ['abbreviation' => 'NOK', 'scale' => 10, 'name' => 'Норвежских крон'],
    456 => ['abbreviation' => 'RUB', 'scale' => 100, 'name' => 'Российских рублей'],
    457 => ['abbreviation' => 'XDR', 'scale' => 1, 'name' => 'СДР (Специальные права заимствования)'],
    458 => ['abbreviation' => 'KGS', 'scale' => 100, 'name' => 'Сомов'],
    459 => ['abbreviation' => 'KZT', 'scale' => 1000, 'name' => 'Тенге'],
    460 => ['abbreviation' => 'TRY', 'scale' => 10, 'name' => 'Турецких лир'],
    461 => ['abbreviation' => 'IRR', 'scale' => 100000, 'name' => 'Иранских риалов'],
    462 => ['abbreviation' => 'CNY', 'scale' => 10, 'name' => 'Китайских юаней'],
    463 => ['abbreviation' => 'CZK', 'scale' => 100, 'name' => 'Чешских крон'],
    464 => ['abbreviation' => 'SEK', 'scale' => 10, 'name' => 'Шведских крон'],
    508 => ['abbreviation' => 'JPY', 'scale' => 100, 'name' => 'Иен'],
    510 => ['abbreviation' => 'AMD', 'scale' => 1000, 'name' => 'Армянских драмов'],
    511 => ['abbreviation' => 'INR', 'scale' => 100, 'name' => 'Индийских рупий'],
    512 => ['abbreviation' => 'VND', 'scale' => 100000, 'name' => 'Донгов'],
    513 => ['abbreviation' => 'AED', 'scale' => 10, 'name' => 'Дирхамов ОАЭ'],
    514 => ['abbreviation' => 'BRL', 'scale' => 10, 'name' => 'Бразильских реалов'],
];
